# Generated by Django 4.2.5 on 2023-09-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_max_guests_alter_room_max_adults'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Hotel-facilites'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(related_name='facilities', to='main.facility'),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_photos', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
