# Generated by Django 4.2.5 on 2023-09-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reservation_room_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('★☆☆☆☆', '1'), ('★★☆☆☆', '2'), ('★★★☆☆', '3'), ('★★★★☆', '4'), ('★★★★★', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to='main.room'),
        ),
    ]
