# Generated by Django 4.2.5 on 2023-09-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
