# Generated by Django 4.2.5 on 2023-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reservation_duration_reservation_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('make_payment', 'Awaiting Payment'), ('pen', 'Pending'), ('can', 'Cancelled'), ('book', 'Booked'), ('ref', 'Refunded')], default='make_payment', max_length=12),
        ),
    ]
